### ISSUE TITLE
喵呜，交换个友链吧！

### ISSUE THREAD

**Issue by CoelacanthusHex** [karuboniru/karuboniru.github.io#5]
标题: 倚窗，听雨 - Coelacanthus' blog
链接: https://blog.lhwcrt.top/
头像: https://cdn.jsdelivr.net/gh/ayalhw/blog@master/static/icon.webp
简介: 凡人难以承受生活的全部真相，于是他们各执一端。

**Comment by karuboniru** [comment]
Done, See https://yanqiyu.info/links/

**Comment by CoelacanthusHex** [comment]
咱博客换域名了，现在域名是 https://blog.coelacanthus.moe 麻烦更新下
（以前是 https://blog.lhwcrt.top
